Male Life Expectancy

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df_total_birth_male= pd.read_excel(r"C:\Users\nxg11006\OneDrive - NXP\Desktop\Datasets\Life expectancy at birth, male (years)\API_SP.DYN.LE00.MA.IN_DS2_en_excel_v2_4191.xls", engine='xlrd')
df_total_birth_male

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69
0,Last Updated Date,2026-07-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.000000,1961.000000,1962.000000,1963.000000,1964.000000,1965.000000,...,2016.00000,2017.000000,2018.000000,2019.000000,2020.000000,2021.000000,2022.000000,2023.000000,2024.000000,2025.0
3,Aruba,ABW,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,60.746000,61.114000,61.371000,61.601000,61.824000,62.047000,...,72.69100,72.802000,72.880000,73.047000,72.344000,70.794000,73.537000,73.702000,73.845000,NaN
4,Africa Eastern and Southern,AFE,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,42.448909,42.681453,43.117691,43.341702,43.682342,43.891466,...,59.73222,60.106818,60.796394,61.289264,61.048093,60.351874,61.765907,62.395579,62.588776,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,47.679000,48.952000,47.534000,49.385000,50.081000,50.721000,...,74.59000,75.086000,74.993000,75.064000,71.865000,72.916000,75.340000,75.804000,76.008000,NaN
264,"Yemen, Rep.",YEM,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,31.105000,31.720000,30.986000,30.567000,32.295000,32.924000,...,64.40300,64.295000,62.311000,63.337000,63.330000,63.090000,65.665000,67.235000,67.366000,NaN
265,South Africa,ZAF,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,50.823000,51.188000,51.707000,51.994000,52.306000,52.490000,...,61.33200,61.980000,62.296000,62.696000,62.174000,59.193000,61.813000,62.609000,62.783000,NaN
266,Zambia,ZMB,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,49.581000,49.998000,50.258000,50.558000,49.851000,50.949000,...,58.91900,59.207000,59.693000,60.349000,60.731000,59.790000,62.768000,63.936000,64.100000,NaN
267,Zimbabwe,ZWE,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,51.077000,51.516000,51.965000,52.413000,52.866000,53.305000,...,57.94000,58.304000,58.852000,58.830000,59.091000,57.717000,59.880000,60.226000,60.492000,NaN

In [4]:
df_total_birth_male.shape

(268, 70)

Dropping first 2 rows - metadata

In [5]:
df_total_birth_male.iloc[2].tolist()[:4]

['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code']

In [6]:
temp_list1 = df_total_birth_male.iloc[2].tolist()[:4] #strings
temp_list2 = df_total_birth_male.iloc[2].tolist()[4:] #integers
temp_list2 = list(map(int, temp_list2))
temp_list1.extend(temp_list2) #creating column headers

In [7]:
df_total_birth_male.columns = temp_list1 #resetting default columns

In [8]:
df_total_birth_male = df_total_birth_male.iloc[3:].reset_index(drop=True)
df_total_birth_male

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Aruba,ABW,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,60.746000,61.114000,61.371000,61.601000,61.824000,62.047000,...,72.691000,72.802000,72.880000,73.047000,72.344000,70.794000,73.537000,73.702000,73.845000,NaN
1,Africa Eastern and Southern,AFE,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,42.448909,42.681453,43.117691,43.341702,43.682342,43.891466,...,59.732220,60.106818,60.796394,61.289264,61.048093,60.351874,61.765907,62.395579,62.588776,NaN
2,Afghanistan,AFG,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,32.136000,32.626000,33.098000,33.543000,34.004000,34.438000,...,60.661000,59.388000,59.175000,59.910000,58.455000,57.052000,63.941000,64.467000,64.704000,NaN
3,Africa Western and Central,AFW,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,35.925673,36.181219,37.031000,37.267402,37.503831,37.777814,...,55.459091,55.651689,56.056296,56.134076,56.208421,56.285184,56.892871,57.739825,57.912290,NaN
4,Angola,AGO,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,36.248000,34.266000,34.489000,34.720000,34.996000,35.236000,...,59.237000,59.727000,60.199000,60.609000,60.509000,60.498000,61.748000,62.099000,62.275000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,Kosovo,XKX,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,47.679000,48.952000,47.534000,49.385000,50.081000,50.721000,...,74.590000,75.086000,74.993000,75.064000,71.865000,72.916000,75.340000,75.804000,76.008000,NaN
261,"Yemen, Rep.",YEM,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,31.105000,31.720000,30.986000,30.567000,32.295000,32.924000,...,64.403000,64.295000,62.311000,63.337000,63.330000,63.090000,65.665000,67.235000,67.366000,NaN
262,South Africa,ZAF,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,50.823000,51.188000,51.707000,51.994000,52.306000,52.490000,...,61.332000,61.980000,62.296000,62.696000,62.174000,59.193000,61.813000,62.609000,62.783000,NaN
263,Zambia,ZMB,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,49.581000,49.998000,50.258000,50.558000,49.851000,50.949000,...,58.919000,59.207000,59.693000,60.349000,60.731000,59.790000,62.768000,63.936000,64.100000,NaN
264,Zimbabwe,ZWE,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,51.077000,51.516000,51.965000,52.413000,52.866000,53.305000,...,57.940000,58.304000,58.852000,58.830000,59.091000,57.717000,59.880000,60.226000,60.492000,NaN

Checking columns with all null values and dropping them.

In [9]:
for i in df_total_birth_male.columns:
    if df_total_birth_male[i].isna().all():
        df_total_birth_male.drop(columns=i, inplace=True)

df_total_birth_male
#column of year 2025 dropped

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Aruba,ABW,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,60.746000,61.114000,61.371000,61.601000,61.824000,62.047000,...,72.496000,72.691000,72.802000,72.880000,73.047000,72.344000,70.794000,73.537000,73.702000,73.845000
1,Africa Eastern and Southern,AFE,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,42.448909,42.681453,43.117691,43.341702,43.682342,43.891466,...,59.359626,59.732220,60.106818,60.796394,61.289264,61.048093,60.351874,61.765907,62.395579,62.588776
2,Afghanistan,AFG,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,32.136000,32.626000,33.098000,33.543000,34.004000,34.438000,...,60.363000,60.661000,59.388000,59.175000,59.910000,58.455000,57.052000,63.941000,64.467000,64.704000
3,Africa Western and Central,AFW,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,35.925673,36.181219,37.031000,37.267402,37.503831,37.777814,...,55.086780,55.459091,55.651689,56.056296,56.134076,56.208421,56.285184,56.892871,57.739825,57.912290
4,Angola,AGO,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,36.248000,34.266000,34.489000,34.720000,34.996000,35.236000,...,58.680000,59.237000,59.727000,60.199000,60.609000,60.509000,60.498000,61.748000,62.099000,62.275000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,Kosovo,XKX,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,47.679000,48.952000,47.534000,49.385000,50.081000,50.721000,...,73.742000,74.590000,75.086000,74.993000,75.064000,71.865000,72.916000,75.340000,75.804000,76.008000
261,"Yemen, Rep.",YEM,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,31.105000,31.720000,30.986000,30.567000,32.295000,32.924000,...,63.985000,64.403000,64.295000,62.311000,63.337000,63.330000,63.090000,65.665000,67.235000,67.366000
262,South Africa,ZAF,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,50.823000,51.188000,51.707000,51.994000,52.306000,52.490000,...,60.802000,61.332000,61.980000,62.296000,62.696000,62.174000,59.193000,61.813000,62.609000,62.783000
263,Zambia,ZMB,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,49.581000,49.998000,50.258000,50.558000,49.851000,50.949000,...,58.545000,58.919000,59.207000,59.693000,60.349000,60.731000,59.790000,62.768000,63.936000,64.100000
264,Zimbabwe,ZWE,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,51.077000,51.516000,51.965000,52.413000,52.866000,53.305000,...,57.330000,57.940000,58.304000,58.852000,58.830000,59.091000,57.717000,59.880000,60.226000,60.492000

In [10]:
len(df_total_birth_male['Country Code'].unique()) #checking if there are redundant values in the columns

265

Combining income data with main df

In [11]:
df_income = pd.read_excel(r"C:\Users\nxg11006\OneDrive - NXP\Desktop\Datasets\Life expectancy at birth, male (years)\API_SP.DYN.LE00.MA.IN_DS2_en_excel_v2_4191.xls", sheet_name='Metadata - Countries',engine='xlrd')

In [12]:
df_income

,Country Code,Region,IncomeGroup,SpecialNotes,TableName
0,ABW,Latin America & Caribbean,High income,NaN,Aruba
1,AFE,NaN,NaN,"26 countries, stretching from the Red Sea in t...",Africa Eastern and Southern
2,AFG,Middle East & North Africa,Low income,The reporting period for national accounts dat...,Afghanistan
3,AFW,NaN,NaN,"22 countries, stretching from the westernmost ...",Africa Western and Central
4,AGO,Sub-Saharan Africa,Lower middle income,The World Bank systematically assesses the app...,Angola
...,...,...,...,...,...
259,XKX,Europe & Central Asia,Upper middle income,NaN,Kosovo
260,YEM,Middle East & North Africa,Low income,The World Bank systematically assesses the app...,"Yemen, Rep."
261,ZAF,Sub-Saharan Africa,Upper middle income,Fiscal year end: March 31; reporting period fo...,South Africa
262,ZMB,Sub-Saharan Africa,Lower middle income,National accounts data were rebased to reflect...,Zambia
263,ZWE,Sub-Saharan Africa,Lower middle income,National Accounts data are reported in Zimbabw...,Zimbabwe

In [13]:
len(df_income['Country Code'].unique())

264

In [14]:
df_income.drop(columns=['SpecialNotes','TableName'], inplace=True)

In [15]:
df_income

    Country Code                      Region          IncomeGroup
0            ABW   Latin America & Caribbean          High income
1            AFE                         NaN                  NaN
2            AFG  Middle East & North Africa           Low income
3            AFW                         NaN                  NaN
4            AGO          Sub-Saharan Africa  Lower middle income
..           ...                         ...                  ...
259          XKX       Europe & Central Asia  Upper middle income
260          YEM  Middle East & North Africa           Low income
261          ZAF          Sub-Saharan Africa  Upper middle income
262          ZMB          Sub-Saharan Africa  Lower middle income
263          ZWE          Sub-Saharan Africa  Lower middle income

[264 rows x 3 columns]

Filling missing values with custom text for better interpretation in 'IncomeGroup' and 'Region' columns.

In [16]:
df_total_birth_male = pd.merge(df_total_birth_male, df_income, on='Country Code')
df_total_birth_male['IncomeGroup'] = df_total_birth_male['IncomeGroup'].fillna('Income Unavailable')
df_total_birth_male['Region'] = df_total_birth_male['Region'].fillna('Region Unavailable')
df_total_birth_male

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,Region,IncomeGroup
0,Aruba,ABW,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,60.746000,61.114000,61.371000,61.601000,61.824000,62.047000,...,72.802000,72.880000,73.047000,72.344000,70.794000,73.537000,73.702000,73.845000,Latin America & Caribbean,High income
1,Africa Eastern and Southern,AFE,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,42.448909,42.681453,43.117691,43.341702,43.682342,43.891466,...,60.106818,60.796394,61.289264,61.048093,60.351874,61.765907,62.395579,62.588776,Region Unavailable,Income Unavailable
2,Afghanistan,AFG,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,32.136000,32.626000,33.098000,33.543000,34.004000,34.438000,...,59.388000,59.175000,59.910000,58.455000,57.052000,63.941000,64.467000,64.704000,Middle East & North Africa,Low income
3,Africa Western and Central,AFW,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,35.925673,36.181219,37.031000,37.267402,37.503831,37.777814,...,55.651689,56.056296,56.134076,56.208421,56.285184,56.892871,57.739825,57.912290,Region Unavailable,Income Unavailable
4,Angola,AGO,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,36.248000,34.266000,34.489000,34.720000,34.996000,35.236000,...,59.727000,60.199000,60.609000,60.509000,60.498000,61.748000,62.099000,62.275000,Sub-Saharan Africa,Lower middle income
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,Kosovo,XKX,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,47.679000,48.952000,47.534000,49.385000,50.081000,50.721000,...,75.086000,74.993000,75.064000,71.865000,72.916000,75.340000,75.804000,76.008000,Europe & Central Asia,Upper middle income
260,"Yemen, Rep.",YEM,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,31.105000,31.720000,30.986000,30.567000,32.295000,32.924000,...,64.295000,62.311000,63.337000,63.330000,63.090000,65.665000,67.235000,67.366000,Middle East & North Africa,Low income
261,South Africa,ZAF,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,50.823000,51.188000,51.707000,51.994000,52.306000,52.490000,...,61.980000,62.296000,62.696000,62.174000,59.193000,61.813000,62.609000,62.783000,Sub-Saharan Africa,Upper middle income
262,Zambia,ZMB,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,49.581000,49.998000,50.258000,50.558000,49.851000,50.949000,...,59.207000,59.693000,60.349000,60.731000,59.790000,62.768000,63.936000,64.100000,Sub-Saharan Africa,Lower middle income
263,Zimbabwe,ZWE,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,51.077000,51.516000,51.965000,52.413000,52.866000,53.305000,...,58.304000,58.852000,58.830000,59.091000,57.717000,59.880000,60.226000,60.492000,Sub-Saharan Africa,Lower middle income

In [17]:
df_total_birth_male.to_csv('df_total_birth_male.csv', index=False) #saving file for dashboard usage.

Female Life Expectancy

In [18]:
df_total_birth_female= pd.read_excel(r"C:\Users\nxg11006\OneDrive - NXP\Desktop\Datasets\Life expectancy at birth, female (years)\API_SP.DYN.LE00.FE.IN_DS2_en_excel_v2_4627.xls", engine='xlrd')
df_total_birth_female

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69
0,Last Updated Date,2026-07-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.000000,1961.000000,1962.000000,1963.000000,1964.000000,1965.000000,...,2016.000000,2017.000000,2018.000000,2019.000000,2020.000000,2021.000000,2022.000000,2023.000000,2024.000000,2025.0
3,Aruba,ABW,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,67.459000,67.394000,67.922000,68.389000,68.902000,69.319000,...,78.203000,78.250000,78.708000,78.814000,78.333000,76.417000,78.691000,78.779000,78.918000,NaN
4,Africa Eastern and Southern,AFE,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,45.998074,46.368461,46.743936,47.094817,47.499206,47.769279,...,64.610039,65.082553,65.872762,66.434436,66.536672,65.652968,67.231203,67.914632,68.129076,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,49.702000,50.806000,49.178000,50.797000,52.154000,53.315000,...,78.864000,79.056000,79.177000,79.363000,76.635000,76.996000,79.811000,80.118000,80.281000,NaN
264,"Yemen, Rep.",YEM,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,36.028000,36.592000,36.670000,36.685000,37.788000,38.534000,...,69.961000,70.122000,69.883000,70.061000,69.805000,69.170000,70.319000,71.388000,71.549000,NaN
265,South Africa,ZAF,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,54.578000,55.218000,55.679000,56.046000,56.363000,56.596000,...,67.916000,68.580000,68.906000,69.216000,67.948000,64.772000,69.037000,69.599000,69.792000,NaN
266,Zambia,ZMB,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,51.708000,52.075000,52.393000,52.638000,52.493000,53.196000,...,63.259000,63.863000,64.533000,65.440000,65.953000,64.925000,67.717000,68.673000,68.874000,NaN
267,Zimbabwe,ZWE,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,55.963000,56.470000,56.993000,57.519000,58.042000,58.548000,...,61.401000,62.016000,62.741000,63.049000,63.747000,62.289000,64.544000,65.013000,65.313000,NaN

In [19]:
df_total_birth_female.shape

(268, 70)

Dropping first 2 rows - metadata

In [20]:
df_total_birth_female.iloc[2].tolist()[:4]

['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code']

In [21]:
temp_list1 = df_total_birth_female.iloc[2].tolist()[:4] #strings
temp_list2 = df_total_birth_female.iloc[2].tolist()[4:] #integers
temp_list2 = list(map(int, temp_list2))
temp_list1.extend(temp_list2) #creating column headers

In [22]:
df_total_birth_female.columns = temp_list1 #resetting default columns

In [23]:
df_total_birth_female = df_total_birth_female.iloc[3:].reset_index(drop=True)
df_total_birth_female

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Aruba,ABW,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,67.459000,67.394000,67.922000,68.389000,68.902000,69.319000,...,78.203000,78.250000,78.708000,78.814000,78.333000,76.417000,78.691000,78.779000,78.918000,NaN
1,Africa Eastern and Southern,AFE,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,45.998074,46.368461,46.743936,47.094817,47.499206,47.769279,...,64.610039,65.082553,65.872762,66.434436,66.536672,65.652968,67.231203,67.914632,68.129076,NaN
2,Afghanistan,AFG,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,33.549000,34.043000,34.502000,34.945000,35.428000,35.900000,...,64.640000,65.606000,65.942000,66.144000,64.656000,64.079000,67.236000,67.536000,67.812000,NaN
3,Africa Western and Central,AFW,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,39.817586,40.120915,40.411312,40.687986,40.969122,41.264519,...,57.330155,57.612962,58.026144,58.200833,58.549753,58.469158,59.138321,59.992347,60.209148,NaN
4,Angola,AGO,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,39.739000,39.885000,40.218000,40.507000,40.813000,41.120000,...,64.009000,64.527000,65.057000,65.506000,65.774000,65.441000,66.753000,67.144000,67.344000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,Kosovo,XKX,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,49.702000,50.806000,49.178000,50.797000,52.154000,53.315000,...,78.864000,79.056000,79.177000,79.363000,76.635000,76.996000,79.811000,80.118000,80.281000,NaN
261,"Yemen, Rep.",YEM,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,36.028000,36.592000,36.670000,36.685000,37.788000,38.534000,...,69.961000,70.122000,69.883000,70.061000,69.805000,69.170000,70.319000,71.388000,71.549000,NaN
262,South Africa,ZAF,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,54.578000,55.218000,55.679000,56.046000,56.363000,56.596000,...,67.916000,68.580000,68.906000,69.216000,67.948000,64.772000,69.037000,69.599000,69.792000,NaN
263,Zambia,ZMB,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,51.708000,52.075000,52.393000,52.638000,52.493000,53.196000,...,63.259000,63.863000,64.533000,65.440000,65.953000,64.925000,67.717000,68.673000,68.874000,NaN
264,Zimbabwe,ZWE,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,55.963000,56.470000,56.993000,57.519000,58.042000,58.548000,...,61.401000,62.016000,62.741000,63.049000,63.747000,62.289000,64.544000,65.013000,65.313000,NaN

Checking columns with all null values and dropping them.

In [24]:
for i in df_total_birth_female.columns:
    if df_total_birth_female[i].isna().all():
        df_total_birth_female.drop(columns=i, inplace=True)

df_total_birth_female
#column of year 2025 dropped

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Aruba,ABW,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,67.459000,67.394000,67.922000,68.389000,68.902000,69.319000,...,78.139000,78.203000,78.250000,78.708000,78.814000,78.333000,76.417000,78.691000,78.779000,78.918000
1,Africa Eastern and Southern,AFE,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,45.998074,46.368461,46.743936,47.094817,47.499206,47.769279,...,64.063478,64.610039,65.082553,65.872762,66.434436,66.536672,65.652968,67.231203,67.914632,68.129076
2,Afghanistan,AFG,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,33.549000,34.043000,34.502000,34.945000,35.428000,35.900000,...,64.178000,64.640000,65.606000,65.942000,66.144000,64.656000,64.079000,67.236000,67.536000,67.812000
3,Africa Western and Central,AFW,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,39.817586,40.120915,40.411312,40.687986,40.969122,41.264519,...,56.992890,57.330155,57.612962,58.026144,58.200833,58.549753,58.469158,59.138321,59.992347,60.209148
4,Angola,AGO,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,39.739000,39.885000,40.218000,40.507000,40.813000,41.120000,...,63.412000,64.009000,64.527000,65.057000,65.506000,65.774000,65.441000,66.753000,67.144000,67.344000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,Kosovo,XKX,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,49.702000,50.806000,49.178000,50.797000,52.154000,53.315000,...,78.306000,78.864000,79.056000,79.177000,79.363000,76.635000,76.996000,79.811000,80.118000,80.281000
261,"Yemen, Rep.",YEM,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,36.028000,36.592000,36.670000,36.685000,37.788000,38.534000,...,69.708000,69.961000,70.122000,69.883000,70.061000,69.805000,69.170000,70.319000,71.388000,71.549000
262,South Africa,ZAF,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,54.578000,55.218000,55.679000,56.046000,56.363000,56.596000,...,67.027000,67.916000,68.580000,68.906000,69.216000,67.948000,64.772000,69.037000,69.599000,69.792000
263,Zambia,ZMB,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,51.708000,52.075000,52.393000,52.638000,52.493000,53.196000,...,62.830000,63.259000,63.863000,64.533000,65.440000,65.953000,64.925000,67.717000,68.673000,68.874000
264,Zimbabwe,ZWE,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,55.963000,56.470000,56.993000,57.519000,58.042000,58.548000,...,60.490000,61.401000,62.016000,62.741000,63.049000,63.747000,62.289000,64.544000,65.013000,65.313000

In [25]:
len(df_total_birth_female['Country Code'].unique()) #checking if there are redundant values in the columns

265

In [26]:
df_income = pd.read_excel(r"C:\Users\nxg11006\OneDrive - NXP\Desktop\Datasets\Life expectancy at birth, female (years)\API_SP.DYN.LE00.FE.IN_DS2_en_excel_v2_4627.xls", sheet_name='Metadata - Countries',engine='xlrd')

In [27]:
df_income

,Country Code,Region,IncomeGroup,SpecialNotes,TableName
0,ABW,Latin America & Caribbean,High income,NaN,Aruba
1,AFE,NaN,NaN,"26 countries, stretching from the Red Sea in t...",Africa Eastern and Southern
2,AFG,Middle East & North Africa,Low income,The reporting period for national accounts dat...,Afghanistan
3,AFW,NaN,NaN,"22 countries, stretching from the westernmost ...",Africa Western and Central
4,AGO,Sub-Saharan Africa,Lower middle income,The World Bank systematically assesses the app...,Angola
...,...,...,...,...,...
259,XKX,Europe & Central Asia,Upper middle income,NaN,Kosovo
260,YEM,Middle East & North Africa,Low income,The World Bank systematically assesses the app...,"Yemen, Rep."
261,ZAF,Sub-Saharan Africa,Upper middle income,Fiscal year end: March 31; reporting period fo...,South Africa
262,ZMB,Sub-Saharan Africa,Lower middle income,National accounts data were rebased to reflect...,Zambia
263,ZWE,Sub-Saharan Africa,Lower middle income,National Accounts data are reported in Zimbabw...,Zimbabwe

In [28]:
len(df_income['Country Code'].unique()) #checking if there are redundant values in the columns

264

In [29]:
df_income.drop(columns=['SpecialNotes','TableName'], inplace=True)

In [30]:
df_income

    Country Code                      Region          IncomeGroup
0            ABW   Latin America & Caribbean          High income
1            AFE                         NaN                  NaN
2            AFG  Middle East & North Africa           Low income
3            AFW                         NaN                  NaN
4            AGO          Sub-Saharan Africa  Lower middle income
..           ...                         ...                  ...
259          XKX       Europe & Central Asia  Upper middle income
260          YEM  Middle East & North Africa           Low income
261          ZAF          Sub-Saharan Africa  Upper middle income
262          ZMB          Sub-Saharan Africa  Lower middle income
263          ZWE          Sub-Saharan Africa  Lower middle income

[264 rows x 3 columns]

Filling missing values with custom text for better interpretation in 'IncomeGroup' and 'Region' columns.

In [31]:
df_total_birth_female = pd.merge(df_total_birth_female, df_income, on='Country Code')
df_total_birth_female['IncomeGroup'] = df_total_birth_female['IncomeGroup'].fillna('Income Unavailable')
df_total_birth_female['Region'] = df_total_birth_female['Region'].fillna('Region Unavailable')
df_total_birth_female

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,Region,IncomeGroup
0,Aruba,ABW,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,67.459000,67.394000,67.922000,68.389000,68.902000,69.319000,...,78.250000,78.708000,78.814000,78.333000,76.417000,78.691000,78.779000,78.918000,Latin America & Caribbean,High income
1,Africa Eastern and Southern,AFE,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,45.998074,46.368461,46.743936,47.094817,47.499206,47.769279,...,65.082553,65.872762,66.434436,66.536672,65.652968,67.231203,67.914632,68.129076,Region Unavailable,Income Unavailable
2,Afghanistan,AFG,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,33.549000,34.043000,34.502000,34.945000,35.428000,35.900000,...,65.606000,65.942000,66.144000,64.656000,64.079000,67.236000,67.536000,67.812000,Middle East & North Africa,Low income
3,Africa Western and Central,AFW,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,39.817586,40.120915,40.411312,40.687986,40.969122,41.264519,...,57.612962,58.026144,58.200833,58.549753,58.469158,59.138321,59.992347,60.209148,Region Unavailable,Income Unavailable
4,Angola,AGO,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,39.739000,39.885000,40.218000,40.507000,40.813000,41.120000,...,64.527000,65.057000,65.506000,65.774000,65.441000,66.753000,67.144000,67.344000,Sub-Saharan Africa,Lower middle income
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,Kosovo,XKX,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,49.702000,50.806000,49.178000,50.797000,52.154000,53.315000,...,79.056000,79.177000,79.363000,76.635000,76.996000,79.811000,80.118000,80.281000,Europe & Central Asia,Upper middle income
260,"Yemen, Rep.",YEM,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,36.028000,36.592000,36.670000,36.685000,37.788000,38.534000,...,70.122000,69.883000,70.061000,69.805000,69.170000,70.319000,71.388000,71.549000,Middle East & North Africa,Low income
261,South Africa,ZAF,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,54.578000,55.218000,55.679000,56.046000,56.363000,56.596000,...,68.580000,68.906000,69.216000,67.948000,64.772000,69.037000,69.599000,69.792000,Sub-Saharan Africa,Upper middle income
262,Zambia,ZMB,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,51.708000,52.075000,52.393000,52.638000,52.493000,53.196000,...,63.863000,64.533000,65.440000,65.953000,64.925000,67.717000,68.673000,68.874000,Sub-Saharan Africa,Lower middle income
263,Zimbabwe,ZWE,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,55.963000,56.470000,56.993000,57.519000,58.042000,58.548000,...,62.016000,62.741000,63.049000,63.747000,62.289000,64.544000,65.013000,65.313000,Sub-Saharan Africa,Lower middle income

In [32]:
df_total_birth_female.to_csv('df_total_birth_female.csv', index=False) #saving file for dashboard usage.

Statistical Analysis


Q1 : For which income group has the difference in average life expectancy of 
men and women changed the most between 1960 and 2023?

In [33]:
import copy
difference = copy.deepcopy(df_total_birth_male.iloc[:,0:4])
difference = pd.concat([difference,copy.deepcopy(df_total_birth_male.iloc[:,-2:])], axis=1)
difference

,Country Name,Country Code,Indicator Name,Indicator Code,Region,IncomeGroup
0,Aruba,ABW,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,Latin America & Caribbean,High income
1,Africa Eastern and Southern,AFE,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,Region Unavailable,Income Unavailable
2,Afghanistan,AFG,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,Middle East & North Africa,Low income
3,Africa Western and Central,AFW,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,Region Unavailable,Income Unavailable
4,Angola,AGO,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,Sub-Saharan Africa,Lower middle income
...,...,...,...,...,...,...
259,Kosovo,XKX,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,Europe & Central Asia,Upper middle income
260,"Yemen, Rep.",YEM,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,Middle East & North Africa,Low income
261,South Africa,ZAF,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,Sub-Saharan Africa,Upper middle income
262,Zambia,ZMB,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,Sub-Saharan Africa,Lower middle income
263,Zimbabwe,ZWE,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,Sub-Saharan Africa,Lower middle income

In [34]:
#difference of life expectancies over the years for male and female
for i in range(1960, 2025, 1):
    difference[i] = abs(df_total_birth_male[i] - df_total_birth_female[i])

Result

In [35]:
#Grouped values based on IncomeGroup for each year
difference['Change'] = abs(difference[1960] - difference[2023])
result1 = (difference.groupby('IncomeGroup')['Change'].max())
print(f"Income Group with significant difference: {result1.idxmax()}")
result1

Income Group with significant difference: Lower middle income

IncomeGroup
High income            6.149000
Income Unavailable     3.444099
Low income             4.552000
Lower middle income    7.831000
Upper middle income    7.221000
Name: Change, dtype: float64

-----------------------------------End of Notebook-----------------------------------------