In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
death_rate_df= pd.read_excel(r"C:\Users\nxg11006\OneDrive - NXP\Desktop\Datasets\Death rate, crude (per 1,000 people)\API_SP.DYN.CDRT.IN_DS2_en_excel_v2_5075.xls", engine='xlrd')
death_rate_df

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69
0,Last Updated Date,2026-07-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.000000,1961.000000,1962.000000,1963.000000,1964.000000,1965.000000,...,2016.000000,2017.000000,2018.000000,2019.000000,2020.000000,2021.000000,2022.000000,2023.000000,2024.000000,2025.0
3,Aruba,ABW,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,7.525000,7.347000,7.066000,6.863000,6.689000,6.572000,...,7.257000,6.594000,6.703000,6.145000,6.842000,8.951000,8.191000,7.582000,7.778000,NaN
4,Africa Eastern and Southern,AFE,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,20.965499,20.745542,20.443071,20.234375,19.903705,19.767112,...,8.242132,8.078787,7.673761,7.462467,7.540204,7.913823,7.245335,6.978787,6.915108,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,18.608000,17.797000,18.603000,17.410000,16.712000,16.131000,...,5.401000,5.390000,5.568000,5.702000,8.553000,7.261000,5.885000,5.871000,5.973000,NaN
264,"Yemen, Rep.",YEM,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,33.784000,33.245000,33.636000,33.880000,32.408000,31.721000,...,5.647000,5.644000,6.114000,5.859000,5.832000,5.953000,5.232000,4.792000,4.734000,NaN
265,South Africa,ZAF,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,14.196000,13.844000,13.516000,13.303000,13.097000,12.952000,...,9.069000,8.830000,8.789000,8.750000,9.683000,11.933000,9.402000,9.239000,9.237000,NaN
266,Zambia,ZMB,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,16.498000,16.250000,16.062000,15.891000,16.087000,15.573000,...,7.203000,7.005000,6.775000,6.482000,6.260000,6.607000,5.583000,5.207000,5.165000,NaN
267,Zimbabwe,ZWE,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,14.164000,13.827000,13.484000,13.140000,12.796000,12.470000,...,8.816000,8.587000,8.321000,8.281000,8.138000,8.782000,7.779000,7.614000,7.498000,NaN

In [3]:
death_rate_df.shape

(268, 70)

Dropping first 2 rows - metadata

In [4]:
death_rate_df.iloc[2].tolist()[:4]

['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code']

In [ ]:
temp_list1 = death_rate_df.iloc[2].tolist()[:4]
temp_list2 = death_rate_df.iloc[2].tolist()[4:]
temp_list2 = list(map(int, temp_list2))
temp_list1.extend(temp_list2) #creating column headers

In [ ]:
death_rate_df.columns = temp_list1 #resetting default columns

In [7]:
death_rate_df = death_rate_df.iloc[3:].reset_index(drop=True)
death_rate_df

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Aruba,ABW,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,7.525000,7.347000,7.066000,6.863000,6.689000,6.572000,...,7.257000,6.594000,6.703000,6.145000,6.842000,8.951000,8.191000,7.582000,7.778000,NaN
1,Africa Eastern and Southern,AFE,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,20.965499,20.745542,20.443071,20.234375,19.903705,19.767112,...,8.242132,8.078787,7.673761,7.462467,7.540204,7.913823,7.245335,6.978787,6.915108,NaN
2,Afghanistan,AFG,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,31.672000,31.129000,30.630000,30.168000,29.672000,29.193000,...,7.320000,7.315000,7.271000,7.064000,7.565000,8.002000,5.993000,5.797000,5.702000,NaN
3,Africa Western and Central,AFW,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,26.442827,26.204642,25.726181,25.533288,25.333235,25.096745,...,11.227936,11.047781,10.761275,10.719179,10.472037,10.420551,10.360263,9.661143,9.574089,NaN
4,Angola,AGO,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,27.055000,28.075000,27.871000,27.648000,27.370000,27.087000,...,8.476000,8.192000,7.928000,7.701000,7.628000,7.619000,7.097000,6.925000,6.840000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,Kosovo,XKX,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,18.608000,17.797000,18.603000,17.410000,16.712000,16.131000,...,5.401000,5.390000,5.568000,5.702000,8.553000,7.261000,5.885000,5.871000,5.973000,NaN
261,"Yemen, Rep.",YEM,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,33.784000,33.245000,33.636000,33.880000,32.408000,31.721000,...,5.647000,5.644000,6.114000,5.859000,5.832000,5.953000,5.232000,4.792000,4.734000,NaN
262,South Africa,ZAF,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,14.196000,13.844000,13.516000,13.303000,13.097000,12.952000,...,9.069000,8.830000,8.789000,8.750000,9.683000,11.933000,9.402000,9.239000,9.237000,NaN
263,Zambia,ZMB,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,16.498000,16.250000,16.062000,15.891000,16.087000,15.573000,...,7.203000,7.005000,6.775000,6.482000,6.260000,6.607000,5.583000,5.207000,5.165000,NaN
264,Zimbabwe,ZWE,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,14.164000,13.827000,13.484000,13.140000,12.796000,12.470000,...,8.816000,8.587000,8.321000,8.281000,8.138000,8.782000,7.779000,7.614000,7.498000,NaN

Checking columns with all null values and dropping them.

In [ ]:
for i in death_rate_df.columns:
    if death_rate_df[i].isna().all():
        death_rate_df.drop(columns=i, inplace=True)

death_rate_df
#column of year 2025 dropped

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Aruba,ABW,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,7.525000,7.347000,7.066000,6.863000,6.689000,6.572000,...,6.367000,7.257000,6.594000,6.703000,6.145000,6.842000,8.951000,8.191000,7.582000,7.778000
1,Africa Eastern and Southern,AFE,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,20.965499,20.745542,20.443071,20.234375,19.903705,19.767112,...,8.414925,8.242132,8.078787,7.673761,7.462467,7.540204,7.913823,7.245335,6.978787,6.915108
2,Afghanistan,AFG,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,31.672000,31.129000,30.630000,30.168000,29.672000,29.193000,...,7.528000,7.320000,7.315000,7.271000,7.064000,7.565000,8.002000,5.993000,5.797000,5.702000
3,Africa Western and Central,AFW,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,26.442827,26.204642,25.726181,25.533288,25.333235,25.096745,...,11.486477,11.227936,11.047781,10.761275,10.719179,10.472037,10.420551,10.360263,9.661143,9.574089
4,Angola,AGO,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,27.055000,28.075000,27.871000,27.648000,27.370000,27.087000,...,8.809000,8.476000,8.192000,7.928000,7.701000,7.628000,7.619000,7.097000,6.925000,6.840000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,Kosovo,XKX,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,18.608000,17.797000,18.603000,17.410000,16.712000,16.131000,...,5.589000,5.401000,5.390000,5.568000,5.702000,8.553000,7.261000,5.885000,5.871000,5.973000
261,"Yemen, Rep.",YEM,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,33.784000,33.245000,33.636000,33.880000,32.408000,31.721000,...,5.773000,5.647000,5.644000,6.114000,5.859000,5.832000,5.953000,5.232000,4.792000,4.734000
262,South Africa,ZAF,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,14.196000,13.844000,13.516000,13.303000,13.097000,12.952000,...,9.217000,9.069000,8.830000,8.789000,8.750000,9.683000,11.933000,9.402000,9.239000,9.237000
263,Zambia,ZMB,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,16.498000,16.250000,16.062000,15.891000,16.087000,15.573000,...,7.402000,7.203000,7.005000,6.775000,6.482000,6.260000,6.607000,5.583000,5.207000,5.165000
264,Zimbabwe,ZWE,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,14.164000,13.827000,13.484000,13.140000,12.796000,12.470000,...,9.180000,8.816000,8.587000,8.321000,8.281000,8.138000,8.782000,7.779000,7.614000,7.498000

Combining income data with main df

In [10]:
df_income = pd.read_excel(r"C:\Users\nxg11006\OneDrive - NXP\Desktop\Datasets\Death rate, crude (per 1,000 people)\API_SP.DYN.CDRT.IN_DS2_en_excel_v2_5075.xls", sheet_name='Metadata - Countries', engine='xlrd')
df_income

,Country Code,Region,IncomeGroup,SpecialNotes,TableName
0,ABW,Latin America & Caribbean,High income,NaN,Aruba
1,AFE,NaN,NaN,"26 countries, stretching from the Red Sea in t...",Africa Eastern and Southern
2,AFG,Middle East & North Africa,Low income,The reporting period for national accounts dat...,Afghanistan
3,AFW,NaN,NaN,"22 countries, stretching from the westernmost ...",Africa Western and Central
4,AGO,Sub-Saharan Africa,Lower middle income,The World Bank systematically assesses the app...,Angola
...,...,...,...,...,...
259,XKX,Europe & Central Asia,Upper middle income,NaN,Kosovo
260,YEM,Middle East & North Africa,Low income,The World Bank systematically assesses the app...,"Yemen, Rep."
261,ZAF,Sub-Saharan Africa,Upper middle income,Fiscal year end: March 31; reporting period fo...,South Africa
262,ZMB,Sub-Saharan Africa,Lower middle income,National accounts data were rebased to reflect...,Zambia
263,ZWE,Sub-Saharan Africa,Lower middle income,National Accounts data are reported in Zimbabw...,Zimbabwe

In [11]:
len(df_income['Country Code'].unique())

264

In [12]:
df_income.drop(columns=['Country Code','SpecialNotes','TableName'], inplace=True)

In [13]:
df_income

                         Region          IncomeGroup
0     Latin America & Caribbean          High income
1                           NaN                  NaN
2    Middle East & North Africa           Low income
3                           NaN                  NaN
4            Sub-Saharan Africa  Lower middle income
..                          ...                  ...
259       Europe & Central Asia  Upper middle income
260  Middle East & North Africa           Low income
261          Sub-Saharan Africa  Upper middle income
262          Sub-Saharan Africa  Lower middle income
263          Sub-Saharan Africa  Lower middle income

[264 rows x 2 columns]

Filling missing values with custom text for better interpretation in 'IncomeGroup' and 'Region' columns.

In [15]:
death_rate_df = pd.concat([death_rate_df, df_income], axis=1)
death_rate_df['IncomeGroup'] = death_rate_df['IncomeGroup'].fillna('Income Unavailable')
death_rate_df['Region'] = death_rate_df['Region'].fillna('Region Unavailable')
death_rate_df

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,Region,IncomeGroup
0,Aruba,ABW,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,7.525000,7.347000,7.066000,6.863000,6.689000,6.572000,...,6.594000,6.703000,6.145000,6.842000,8.951000,8.191000,7.582000,7.778000,Latin America & Caribbean,High income
1,Africa Eastern and Southern,AFE,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,20.965499,20.745542,20.443071,20.234375,19.903705,19.767112,...,8.078787,7.673761,7.462467,7.540204,7.913823,7.245335,6.978787,6.915108,Region Unavailable,Income Unavailable
2,Afghanistan,AFG,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,31.672000,31.129000,30.630000,30.168000,29.672000,29.193000,...,7.315000,7.271000,7.064000,7.565000,8.002000,5.993000,5.797000,5.702000,Middle East & North Africa,Low income
3,Africa Western and Central,AFW,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,26.442827,26.204642,25.726181,25.533288,25.333235,25.096745,...,11.047781,10.761275,10.719179,10.472037,10.420551,10.360263,9.661143,9.574089,Region Unavailable,Income Unavailable
4,Angola,AGO,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,27.055000,28.075000,27.871000,27.648000,27.370000,27.087000,...,8.192000,7.928000,7.701000,7.628000,7.619000,7.097000,6.925000,6.840000,Sub-Saharan Africa,Lower middle income
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,Kosovo,XKX,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,18.608000,17.797000,18.603000,17.410000,16.712000,16.131000,...,5.390000,5.568000,5.702000,8.553000,7.261000,5.885000,5.871000,5.973000,Middle East & North Africa,Low income
261,"Yemen, Rep.",YEM,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,33.784000,33.245000,33.636000,33.880000,32.408000,31.721000,...,5.644000,6.114000,5.859000,5.832000,5.953000,5.232000,4.792000,4.734000,Sub-Saharan Africa,Upper middle income
262,South Africa,ZAF,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,14.196000,13.844000,13.516000,13.303000,13.097000,12.952000,...,8.830000,8.789000,8.750000,9.683000,11.933000,9.402000,9.239000,9.237000,Sub-Saharan Africa,Lower middle income
263,Zambia,ZMB,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,16.498000,16.250000,16.062000,15.891000,16.087000,15.573000,...,7.005000,6.775000,6.482000,6.260000,6.607000,5.583000,5.207000,5.165000,Sub-Saharan Africa,Lower middle income
264,Zimbabwe,ZWE,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,14.164000,13.827000,13.484000,13.140000,12.796000,12.470000,...,8.587000,8.321000,8.281000,8.138000,8.782000,7.779000,7.614000,7.498000,Region Unavailable,Income Unavailable

In [ ]:
death_rate_df.to_csv('death_rate_df.csv', index=False) #saving file for dashboard usage.