In [3]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df_total_birth_female= pd.read_excel(r"C:\Users\nxg11006\OneDrive - NXP\Desktop\Datasets\Life expectancy at birth, female (years)\API_SP.DYN.LE00.FE.IN_DS2_en_excel_v2_4627.xls", engine='xlrd')
df_total_birth_female

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69
0,Last Updated Date,2026-07-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.000000,1961.000000,1962.000000,1963.000000,1964.000000,1965.000000,...,2016.000000,2017.000000,2018.000000,2019.000000,2020.000000,2021.000000,2022.000000,2023.000000,2024.000000,2025.0
3,Aruba,ABW,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,67.459000,67.394000,67.922000,68.389000,68.902000,69.319000,...,78.203000,78.250000,78.708000,78.814000,78.333000,76.417000,78.691000,78.779000,78.918000,NaN
4,Africa Eastern and Southern,AFE,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,45.998074,46.368461,46.743936,47.094817,47.499206,47.769279,...,64.610039,65.082553,65.872762,66.434436,66.536672,65.652968,67.231203,67.914632,68.129076,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,49.702000,50.806000,49.178000,50.797000,52.154000,53.315000,...,78.864000,79.056000,79.177000,79.363000,76.635000,76.996000,79.811000,80.118000,80.281000,NaN
264,"Yemen, Rep.",YEM,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,36.028000,36.592000,36.670000,36.685000,37.788000,38.534000,...,69.961000,70.122000,69.883000,70.061000,69.805000,69.170000,70.319000,71.388000,71.549000,NaN
265,South Africa,ZAF,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,54.578000,55.218000,55.679000,56.046000,56.363000,56.596000,...,67.916000,68.580000,68.906000,69.216000,67.948000,64.772000,69.037000,69.599000,69.792000,NaN
266,Zambia,ZMB,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,51.708000,52.075000,52.393000,52.638000,52.493000,53.196000,...,63.259000,63.863000,64.533000,65.440000,65.953000,64.925000,67.717000,68.673000,68.874000,NaN
267,Zimbabwe,ZWE,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,55.963000,56.470000,56.993000,57.519000,58.042000,58.548000,...,61.401000,62.016000,62.741000,63.049000,63.747000,62.289000,64.544000,65.013000,65.313000,NaN

In [5]:
df_total_birth_female.shape

(268, 70)

Dropping first 2 rows - metadata

In [6]:
df_total_birth_female.iloc[2].tolist()[:4]

['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code']

In [7]:
temp_list1 = df_total_birth_female.iloc[2].tolist()[:4]
temp_list2 = df_total_birth_female.iloc[2].tolist()[4:]
temp_list2 = list(map(int, temp_list2))
temp_list1.extend(temp_list2)
# temp_list.astype(str)

In [8]:
df_total_birth_female.columns = temp_list1

In [9]:
df_total_birth_female = df_total_birth_female.iloc[3:].reset_index(drop=True)
df_total_birth_female

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Aruba,ABW,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,67.459000,67.394000,67.922000,68.389000,68.902000,69.319000,...,78.203000,78.250000,78.708000,78.814000,78.333000,76.417000,78.691000,78.779000,78.918000,NaN
1,Africa Eastern and Southern,AFE,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,45.998074,46.368461,46.743936,47.094817,47.499206,47.769279,...,64.610039,65.082553,65.872762,66.434436,66.536672,65.652968,67.231203,67.914632,68.129076,NaN
2,Afghanistan,AFG,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,33.549000,34.043000,34.502000,34.945000,35.428000,35.900000,...,64.640000,65.606000,65.942000,66.144000,64.656000,64.079000,67.236000,67.536000,67.812000,NaN
3,Africa Western and Central,AFW,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,39.817586,40.120915,40.411312,40.687986,40.969122,41.264519,...,57.330155,57.612962,58.026144,58.200833,58.549753,58.469158,59.138321,59.992347,60.209148,NaN
4,Angola,AGO,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,39.739000,39.885000,40.218000,40.507000,40.813000,41.120000,...,64.009000,64.527000,65.057000,65.506000,65.774000,65.441000,66.753000,67.144000,67.344000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,Kosovo,XKX,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,49.702000,50.806000,49.178000,50.797000,52.154000,53.315000,...,78.864000,79.056000,79.177000,79.363000,76.635000,76.996000,79.811000,80.118000,80.281000,NaN
261,"Yemen, Rep.",YEM,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,36.028000,36.592000,36.670000,36.685000,37.788000,38.534000,...,69.961000,70.122000,69.883000,70.061000,69.805000,69.170000,70.319000,71.388000,71.549000,NaN
262,South Africa,ZAF,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,54.578000,55.218000,55.679000,56.046000,56.363000,56.596000,...,67.916000,68.580000,68.906000,69.216000,67.948000,64.772000,69.037000,69.599000,69.792000,NaN
263,Zambia,ZMB,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,51.708000,52.075000,52.393000,52.638000,52.493000,53.196000,...,63.259000,63.863000,64.533000,65.440000,65.953000,64.925000,67.717000,68.673000,68.874000,NaN
264,Zimbabwe,ZWE,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,55.963000,56.470000,56.993000,57.519000,58.042000,58.548000,...,61.401000,62.016000,62.741000,63.049000,63.747000,62.289000,64.544000,65.013000,65.313000,NaN

Checking columns with all null values and dropping them.

In [10]:
for i in df_total_birth_female.columns:
    if df_total_birth_female[i].isna().all():
        df_total_birth_female.drop(columns=i, inplace=True)

df_total_birth_female

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Aruba,ABW,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,67.459000,67.394000,67.922000,68.389000,68.902000,69.319000,...,78.139000,78.203000,78.250000,78.708000,78.814000,78.333000,76.417000,78.691000,78.779000,78.918000
1,Africa Eastern and Southern,AFE,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,45.998074,46.368461,46.743936,47.094817,47.499206,47.769279,...,64.063478,64.610039,65.082553,65.872762,66.434436,66.536672,65.652968,67.231203,67.914632,68.129076
2,Afghanistan,AFG,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,33.549000,34.043000,34.502000,34.945000,35.428000,35.900000,...,64.178000,64.640000,65.606000,65.942000,66.144000,64.656000,64.079000,67.236000,67.536000,67.812000
3,Africa Western and Central,AFW,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,39.817586,40.120915,40.411312,40.687986,40.969122,41.264519,...,56.992890,57.330155,57.612962,58.026144,58.200833,58.549753,58.469158,59.138321,59.992347,60.209148
4,Angola,AGO,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,39.739000,39.885000,40.218000,40.507000,40.813000,41.120000,...,63.412000,64.009000,64.527000,65.057000,65.506000,65.774000,65.441000,66.753000,67.144000,67.344000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,Kosovo,XKX,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,49.702000,50.806000,49.178000,50.797000,52.154000,53.315000,...,78.306000,78.864000,79.056000,79.177000,79.363000,76.635000,76.996000,79.811000,80.118000,80.281000
261,"Yemen, Rep.",YEM,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,36.028000,36.592000,36.670000,36.685000,37.788000,38.534000,...,69.708000,69.961000,70.122000,69.883000,70.061000,69.805000,69.170000,70.319000,71.388000,71.549000
262,South Africa,ZAF,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,54.578000,55.218000,55.679000,56.046000,56.363000,56.596000,...,67.027000,67.916000,68.580000,68.906000,69.216000,67.948000,64.772000,69.037000,69.599000,69.792000
263,Zambia,ZMB,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,51.708000,52.075000,52.393000,52.638000,52.493000,53.196000,...,62.830000,63.259000,63.863000,64.533000,65.440000,65.953000,64.925000,67.717000,68.673000,68.874000
264,Zimbabwe,ZWE,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,55.963000,56.470000,56.993000,57.519000,58.042000,58.548000,...,60.490000,61.401000,62.016000,62.741000,63.049000,63.747000,62.289000,64.544000,65.013000,65.313000

In [11]:
len(df_total_birth_female['Country Code'].unique())

265

In [13]:
df_income = pd.read_excel(r"C:\Users\nxg11006\OneDrive - NXP\Desktop\Datasets\Life expectancy at birth, female (years)\API_SP.DYN.LE00.FE.IN_DS2_en_excel_v2_4627.xls", sheet_name='Metadata - Countries',engine='xlrd')

In [14]:
df_income

,Country Code,Region,IncomeGroup,SpecialNotes,TableName
0,ABW,Latin America & Caribbean,High income,NaN,Aruba
1,AFE,NaN,NaN,"26 countries, stretching from the Red Sea in t...",Africa Eastern and Southern
2,AFG,Middle East & North Africa,Low income,The reporting period for national accounts dat...,Afghanistan
3,AFW,NaN,NaN,"22 countries, stretching from the westernmost ...",Africa Western and Central
4,AGO,Sub-Saharan Africa,Lower middle income,The World Bank systematically assesses the app...,Angola
...,...,...,...,...,...
259,XKX,Europe & Central Asia,Upper middle income,NaN,Kosovo
260,YEM,Middle East & North Africa,Low income,The World Bank systematically assesses the app...,"Yemen, Rep."
261,ZAF,Sub-Saharan Africa,Upper middle income,Fiscal year end: March 31; reporting period fo...,South Africa
262,ZMB,Sub-Saharan Africa,Lower middle income,National accounts data were rebased to reflect...,Zambia
263,ZWE,Sub-Saharan Africa,Lower middle income,National Accounts data are reported in Zimbabw...,Zimbabwe

In [15]:
len(df_income['Country Code'].unique())

264

In [16]:
df_income.drop(columns=['SpecialNotes','TableName'], inplace=True)

In [17]:
df_income

    Country Code                      Region          IncomeGroup
0            ABW   Latin America & Caribbean          High income
1            AFE                         NaN                  NaN
2            AFG  Middle East & North Africa           Low income
3            AFW                         NaN                  NaN
4            AGO          Sub-Saharan Africa  Lower middle income
..           ...                         ...                  ...
259          XKX       Europe & Central Asia  Upper middle income
260          YEM  Middle East & North Africa           Low income
261          ZAF          Sub-Saharan Africa  Upper middle income
262          ZMB          Sub-Saharan Africa  Lower middle income
263          ZWE          Sub-Saharan Africa  Lower middle income

[264 rows x 3 columns]

In [18]:
df_total_birth_female = pd.merge(df_total_birth_female, df_income, on='Country Code')
df_total_birth_female['IncomeGroup'] = df_total_birth_female['IncomeGroup'].fillna('Income Unavailable')
df_total_birth_female['Region'] = df_total_birth_female['Region'].fillna('Region Unavailable')
df_total_birth_female

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,Region,IncomeGroup
0,Aruba,ABW,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,67.459000,67.394000,67.922000,68.389000,68.902000,69.319000,...,78.250000,78.708000,78.814000,78.333000,76.417000,78.691000,78.779000,78.918000,Latin America & Caribbean,High income
1,Africa Eastern and Southern,AFE,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,45.998074,46.368461,46.743936,47.094817,47.499206,47.769279,...,65.082553,65.872762,66.434436,66.536672,65.652968,67.231203,67.914632,68.129076,Region Unavailable,Income Unavailable
2,Afghanistan,AFG,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,33.549000,34.043000,34.502000,34.945000,35.428000,35.900000,...,65.606000,65.942000,66.144000,64.656000,64.079000,67.236000,67.536000,67.812000,Middle East & North Africa,Low income
3,Africa Western and Central,AFW,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,39.817586,40.120915,40.411312,40.687986,40.969122,41.264519,...,57.612962,58.026144,58.200833,58.549753,58.469158,59.138321,59.992347,60.209148,Region Unavailable,Income Unavailable
4,Angola,AGO,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,39.739000,39.885000,40.218000,40.507000,40.813000,41.120000,...,64.527000,65.057000,65.506000,65.774000,65.441000,66.753000,67.144000,67.344000,Sub-Saharan Africa,Lower middle income
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,Kosovo,XKX,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,49.702000,50.806000,49.178000,50.797000,52.154000,53.315000,...,79.056000,79.177000,79.363000,76.635000,76.996000,79.811000,80.118000,80.281000,Europe & Central Asia,Upper middle income
260,"Yemen, Rep.",YEM,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,36.028000,36.592000,36.670000,36.685000,37.788000,38.534000,...,70.122000,69.883000,70.061000,69.805000,69.170000,70.319000,71.388000,71.549000,Middle East & North Africa,Low income
261,South Africa,ZAF,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,54.578000,55.218000,55.679000,56.046000,56.363000,56.596000,...,68.580000,68.906000,69.216000,67.948000,64.772000,69.037000,69.599000,69.792000,Sub-Saharan Africa,Upper middle income
262,Zambia,ZMB,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,51.708000,52.075000,52.393000,52.638000,52.493000,53.196000,...,63.863000,64.533000,65.440000,65.953000,64.925000,67.717000,68.673000,68.874000,Sub-Saharan Africa,Lower middle income
263,Zimbabwe,ZWE,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,55.963000,56.470000,56.993000,57.519000,58.042000,58.548000,...,62.016000,62.741000,63.049000,63.747000,62.289000,64.544000,65.013000,65.313000,Sub-Saharan Africa,Lower middle income